import type { PipelineDeal, PipelineStage, PipelineWorkflow } from "@/lib/pipeline-types";

const newSalesStages: PipelineStage[] = [
  { id: "lead", name: "Lead", probability: 10, status: "open", position: 1 },
  { id: "validado", name: "Validado", probability: 20, status: "open", position: 2 },
  { id: "cita-cliente", name: "Cita cliente", probability: 30, status: "open", position: 3 },
  { id: "calificado", name: "Calificado", probability: 45, status: "open", position: 4 },
  { id: "propuesta", name: "Propuesta", probability: 60, status: "open", position: 5 },
  { id: "negociacion", name: "Negociación", probability: 75, status: "open", position: 6 },
  { id: "si-verbal", name: "Sí verbal", probability: 90, status: "open", position: 7 },
  { id: "contrato", name: "Contrato", probability: 95, status: "open", position: 8 },
  { id: "ganado", name: "Ganado", probability: 100, status: "won", position: 9 },
  { id: "perdido", name: "Perdido", probability: 0, status: "lost", position: 10 }
];

export const pipelineDemoWorkflows: PipelineWorkflow[] = [
  {
    id: "new-sales",
    name: "Captacion inmobiliaria demo",
    description: "Flujo comercial principal para oportunidades inmobiliarias de demostracion.",
    stages: [...newSalesStages]
  }
];

export const pipelineDemoDeals: PipelineDeal[] = [
  {
    id: "deal-pipeline-001",
    pipelineId: "new-sales",
    title: "Captacion Bosque Verde Industrial",
    client: "Valentina Cruz",
    company: "Bosque Verde Capital",
    amount: 185000,
    currency: "MXN",
    stage: "lead",
    probability: 10,
    status: "open",
    closeDate: "2026-04-24",
    owner: "Mariana Fuentes",
    aiPulse: false
  },
  {
    id: "deal-pipeline-002",
    pipelineId: "new-sales",
    title: "Compra familiar Vista Encino",
    client: "Paola Serrano",
    company: "Familia Serrano",
    amount: 8350000,
    currency: "MXN",
    stage: "lead",
    probability: 12,
    status: "open",
    closeDate: "2026-05-03",
    owner: "Luis Navarro",
    aiPulse: true
  },
  {
    id: "deal-pipeline-003",
    pipelineId: "new-sales",
    title: "Arboledas Oficinas corporativo",
    client: "Fondo Horizonte",
    company: "Horizonte Advisory",
    amount: 190000,
    currency: "MXN",
    stage: "validado",
    probability: 20,
    status: "open",
    closeDate: "2026-04-18",
    owner: "Carlos Herrera",
    aiPulse: true
  },
  {
    id: "deal-pipeline-004",
    pipelineId: "new-sales",
    title: "Torre Central 402 relocation",
    client: "Monica Rivas",
    company: "Torre Central Advisory",
    amount: 118000,
    currency: "MXN",
    stage: "validado",
    probability: 22,
    status: "open",
    closeDate: "2026-04-15",
    owner: "Mariana Fuentes",
    aiPulse: false
  },
  {
    id: "deal-pipeline-005",
    pipelineId: "new-sales",
    title: "Jardines Premier local demo",
    client: "Paula Serrano",
    company: "Premier Retail Demo",
    amount: 82000,
    currency: "MXN",
    stage: "cita-cliente",
    probability: 30,
    status: "open",
    closeDate: "2026-04-12",
    owner: "Julieta Mora",
    aiPulse: false
  },
  {
    id: "deal-pipeline-006",
    pipelineId: "new-sales",
    title: "Puerta del Sol terreno inversion",
    client: "Clara Montes",
    company: "Montes Patrimonial",
    amount: 4760000,
    currency: "MXN",
    stage: "cita-cliente",
    probability: 32,
    status: "open",
    closeDate: "2026-04-20",
    owner: "Andrea Lozano",
    aiPulse: true
  },
  {
    id: "deal-pipeline-007",
    pipelineId: "new-sales",
    title: "Residencial Altaria reposicionamiento",
    client: "Valentina Cruz",
    company: "Altaria Patrimonial",
    amount: 6120000,
    currency: "MXN",
    stage: "calificado",
    probability: 45,
    status: "open",
    closeDate: "2026-04-09",
    owner: "Andrea Lozano",
    aiPulse: false
  },
  {
    id: "deal-pipeline-008",
    pipelineId: "new-sales",
    title: "Expansion Bosque Verde logistico",
    client: "Grupo Horizonte",
    company: "Grupo Horizonte",
    amount: 187500,
    currency: "MXN",
    stage: "calificado",
    probability: 45,
    status: "open",
    closeDate: "2026-04-25",
    owner: "Carlos Herrera",
    aiPulse: true
  },
  {
    id: "deal-pipeline-009",
    pipelineId: "new-sales",
    title: "Vista Encino open house",
    client: "Monica Rivas",
    company: "Familia Vargas Rivas",
    amount: 8350000,
    currency: "MXN",
    stage: "calificado",
    probability: 48,
    status: "open",
    closeDate: "2026-06-12",
    owner: "Alejandra Rios",
    aiPulse: false
  },
  {
    id: "deal-pipeline-010",
    pipelineId: "new-sales",
    title: "Torre Central 402 cierre ejecutivo",
    client: "Torre Central Advisory",
    company: "Torre Central Advisory",
    amount: 118000,
    currency: "MXN",
    stage: "calificado",
    probability: 50,
    status: "open",
    closeDate: "2026-05-09",
    owner: "Mariana Fuentes",
    aiPulse: false
  },
  {
    id: "deal-pipeline-011",
    pipelineId: "new-sales",
    title: "Arboledas Oficinas renta premium",
    client: "Fondo Arboleda",
    company: "Arboleda Corporate",
    amount: 210000,
    currency: "MXN",
    stage: "propuesta",
    probability: 60,
    status: "open",
    closeDate: "2026-04-30",
    owner: "Carlos Herrera",
    aiPulse: true
  },
  {
    id: "deal-pipeline-012",
    pipelineId: "new-sales",
    title: "Bosque Verde contrato borrador",
    client: "Bosque Verde Capital",
    company: "Bosque Verde Capital",
    amount: 187500,
    currency: "MXN",
    stage: "propuesta",
    probability: 63,
    status: "open",
    closeDate: "2026-04-08",
    owner: "Mariana Fuentes",
    aiPulse: false
  },
  {
    id: "deal-pipeline-013",
    pipelineId: "new-sales",
    title: "Jardines Premier firma comercial",
    client: "Paula Serrano",
    company: "Premier Retail Demo",
    amount: 82000,
    currency: "MXN",
    stage: "negociacion",
    probability: 75,
    status: "open",
    closeDate: "2026-04-16",
    owner: "Julieta Mora",
    aiPulse: false
  },
  {
    id: "deal-pipeline-014",
    pipelineId: "new-sales",
    title: "Vista Encino compra final",
    client: "Emilio Vargas",
    company: "Familia Vargas Rivas",
    amount: 8200000,
    currency: "MXN",
    stage: "negociacion",
    probability: 78,
    status: "open",
    closeDate: "2026-04-21",
    owner: "Alejandra Rios",
    aiPulse: true
  },
  {
    id: "deal-pipeline-015",
    pipelineId: "new-sales",
    title: "Torre Central 402 suite 8",
    client: "Torre Central Advisory",
    company: "Torre Central Advisory",
    amount: 118000,
    currency: "MXN",
    stage: "si-verbal",
    probability: 90,
    status: "open",
    closeDate: "2026-04-05",
    owner: "Mariana Fuentes",
    aiPulse: false
  },
  {
    id: "deal-pipeline-016",
    pipelineId: "new-sales",
    title: "Bosque Verde cierre logistica",
    client: "Grupo Horizonte",
    company: "Bosque Verde Capital",
    amount: 185000,
    currency: "MXN",
    stage: "si-verbal",
    probability: 92,
    status: "open",
    closeDate: "2026-04-10",
    owner: "Carlos Herrera",
    aiPulse: true
  },
  {
    id: "deal-pipeline-017",
    pipelineId: "new-sales",
    title: "Contrato Arboledas Oficinas",
    client: "Fondo Arboleda",
    company: "Arboleda Corporate",
    amount: 210000,
    currency: "MXN",
    stage: "contrato",
    probability: 95,
    status: "open",
    closeDate: "2026-04-07",
    owner: "Carlos Herrera",
    aiPulse: true
  },
  {
    id: "deal-pipeline-018",
    pipelineId: "new-sales",
    title: "Ganado Jardines Premier local 3",
    client: "Paula Serrano",
    company: "Premier Retail Demo",
    amount: 82000,
    currency: "MXN",
    stage: "ganado",
    probability: 100,
    status: "won",
    closeDate: "2026-03-18",
    owner: "Julieta Mora",
    aiPulse: false
  },
  {
    id: "deal-pipeline-019",
    pipelineId: "new-sales",
    title: "Ganado valuacion Bosque Verde",
    client: "Roberto Mena",
    company: "Altaria Patrimonial",
    amount: 25000,
    currency: "MXN",
    stage: "ganado",
    probability: 100,
    status: "won",
    closeDate: "2026-03-22",
    owner: "Carlos Herrera",
    aiPulse: false
  },
  {
    id: "deal-pipeline-020",
    pipelineId: "new-sales",
    title: "Perdido Residencial Altaria reactivacion",
    client: "Valentina Cruz",
    company: "Altaria Patrimonial",
    amount: 6120000,
    currency: "MXN",
    stage: "perdido",
    probability: 0,
    status: "lost",
    closeDate: "2026-03-11",
    owner: "Andrea Lozano",
    aiPulse: false
  }
];
