import type { PipelineDeal, PipelineStage, PipelineWorkflow } from "@/lib/pipeline-types";

const newSalesStages: PipelineStage[] = [
  { id: "lead", name: "Lead", probability: 10, status: "open", position: 1 },
  { id: "validado", name: "Validado", probability: 20, status: "open", position: 2 },
  { id: "cita-cliente", name: "Cita cliente", probability: 30, status: "open", position: 3 },
  { id: "calificado", name: "Calificado", probability: 45, status: "open", position: 4 },
  { id: "propuesta", name: "Propuesta", probability: 60, status: "open", position: 5 },
  { id: "negociacion", name: "Negociación", probability: 75, status: "open", position: 6 },
  { id: "si-verbal", name: "Sí verbal", probability: 90, status: "open", position: 7 },
  { id: "contrato", name: "Contrato", probability: 95, status: "open", position: 8 },
  { id: "ganado", name: "Ganado", probability: 100, status: "won", position: 9 },
  { id: "perdido", name: "Perdido", probability: 0, status: "lost", position: 10 }
];

export const pipelineDemoWorkflows: PipelineWorkflow[] = [
  {
    id: "new-sales",
    name: "New Sales",
    description: "Flujo comercial principal para nuevas oportunidades.",
    stages: [...newSalesStages]
  }
];

export const pipelineDemoDeals: PipelineDeal[] = [
  {
    id: "deal-pipeline-001",
    pipelineId: "new-sales",
    title: "Auditoría fiscal Grupo Sierra",
    client: "Fernanda Soto",
    company: "Grupo Sierra",
    amount: 42000,
    currency: "MXN",
    stage: "lead",
    probability: 10,
    status: "open",
    closeDate: "2026-04-24",
    owner: "Lucia Herrera",
    aiPulse: false
  },
  {
    id: "deal-pipeline-002",
    pipelineId: "new-sales",
    title: "Renovación portal industrial",
    client: "Carlos Mendez",
    company: "Nortech",
    amount: 8600,
    currency: "USD",
    stage: "lead",
    probability: 12,
    status: "open",
    closeDate: "2026-05-03",
    owner: "Mateo Ruiz",
    aiPulse: true
  },
  {
    id: "deal-pipeline-003",
    pipelineId: "new-sales",
    title: "Bernardo Felix Dias Dashboard GPS",
    client: "Bernardo",
    company: "Transocean",
    amount: 3000,
    currency: "USD",
    stage: "validado",
    probability: 20,
    status: "open",
    closeDate: "2026-04-18",
    owner: "Lucia Herrera",
    aiPulse: true
  },
  {
    id: "deal-pipeline-004",
    pipelineId: "new-sales",
    title: "SEO Esposa Manuel Rivera",
    client: "Manuel Rivera",
    company: "Rivera Studio",
    amount: 18000,
    currency: "MXN",
    stage: "validado",
    probability: 22,
    status: "open",
    closeDate: "2026-04-15",
    owner: "Mateo Ruiz",
    aiPulse: false
  },
  {
    id: "deal-pipeline-005",
    pipelineId: "new-sales",
    title: "Discovery omnicanal Andina",
    client: "Sofia Rojas",
    company: "Andina Foods",
    amount: 12500,
    currency: "USD",
    stage: "cita-cliente",
    probability: 30,
    status: "open",
    closeDate: "2026-04-12",
    owner: "Lucia Herrera",
    aiPulse: false
  },
  {
    id: "deal-pipeline-006",
    pipelineId: "new-sales",
    title: "Automatización cobranza Riviera",
    client: "Elena Prado",
    company: "Riviera Hoteles",
    amount: 68000,
    currency: "MXN",
    stage: "cita-cliente",
    probability: 32,
    status: "open",
    closeDate: "2026-04-20",
    owner: "Valeria Cruz",
    aiPulse: true
  },
  {
    id: "deal-pipeline-007",
    pipelineId: "new-sales",
    title: "Sitio Capitan Salinas",
    client: "Salinas",
    company: "Heliamexico",
    amount: 10000,
    currency: "MXN",
    stage: "calificado",
    probability: 45,
    status: "open",
    closeDate: "2026-04-09",
    owner: "Mateo Ruiz",
    aiPulse: false
  },
  {
    id: "deal-pipeline-008",
    pipelineId: "new-sales",
    title: "Keptos Operations HUB",
    client: "BRassart",
    company: "Keptos",
    amount: 3000,
    currency: "USD",
    stage: "calificado",
    probability: 45,
    status: "open",
    closeDate: "2026-04-25",
    owner: "Lucia Herrera",
    aiPulse: true
  },
  {
    id: "deal-pipeline-009",
    pipelineId: "new-sales",
    title: "Instalación 55 plantas eléctricas",
    client: "Laura Paredes",
    company: "Cimarron SA",
    amount: 550000,
    currency: "USD",
    stage: "calificado",
    probability: 48,
    status: "open",
    closeDate: "2026-06-12",
    owner: "Valeria Cruz",
    aiPulse: false
  },
  {
    id: "deal-pipeline-010",
    pipelineId: "new-sales",
    title: "Grupo Bimbo soporte nacional",
    client: "Alejandro Rodriguez",
    company: "Grupo Bimbo",
    amount: 250000,
    currency: "MXN",
    stage: "calificado",
    probability: 50,
    status: "open",
    closeDate: "2026-05-09",
    owner: "Mateo Ruiz",
    aiPulse: false
  },
  {
    id: "deal-pipeline-011",
    pipelineId: "new-sales",
    title: "ERP - Pedro Leyva",
    client: "Pedro Leyva",
    company: "Grupo Leyva",
    amount: 390000,
    currency: "MXN",
    stage: "propuesta",
    probability: 60,
    status: "open",
    closeDate: "2026-04-30",
    owner: "Lucia Herrera",
    aiPulse: true
  },
  {
    id: "deal-pipeline-012",
    pipelineId: "new-sales",
    title: "Cinco Seis",
    client: "Catalina Vergas",
    company: "Cinco Seis",
    amount: 3650,
    currency: "USD",
    stage: "propuesta",
    probability: 63,
    status: "open",
    closeDate: "2026-04-08",
    owner: "Valeria Cruz",
    aiPulse: false
  },
  {
    id: "deal-pipeline-013",
    pipelineId: "new-sales",
    title: "Migration Astro + SEO",
    client: "Mauricio Cervantes",
    company: "Kinich Studios",
    amount: 2750,
    currency: "MXN",
    stage: "propuesta",
    probability: 58,
    status: "open",
    closeDate: "2026-04-19",
    owner: "Mateo Ruiz",
    aiPulse: true
  },
  {
    id: "deal-pipeline-014",
    pipelineId: "new-sales",
    title: "Murmullo Ensueño",
    client: "Jacques Baldassari",
    company: "Murmullo Ensueño",
    amount: 738,
    currency: "MXN",
    stage: "propuesta",
    probability: 62,
    status: "open",
    closeDate: "2026-04-11",
    owner: "Lucia Herrera",
    aiPulse: false
  },
  {
    id: "deal-pipeline-015",
    pipelineId: "new-sales",
    title: "Projet Ecommerce Catalina",
    client: "Catalina Vergas",
    company: "Catalina Studio",
    amount: 75000,
    currency: "MXN",
    stage: "negociacion",
    probability: 75,
    status: "open",
    closeDate: "2026-04-16",
    owner: "Valeria Cruz",
    aiPulse: false
  },
  {
    id: "deal-pipeline-016",
    pipelineId: "new-sales",
    title: "Client site web refaire",
    client: "GESCO",
    company: "GESCO",
    amount: 2500,
    currency: "CAD",
    stage: "negociacion",
    probability: 78,
    status: "open",
    closeDate: "2026-04-21",
    owner: "Mateo Ruiz",
    aiPulse: false
  },
  {
    id: "deal-pipeline-017",
    pipelineId: "new-sales",
    title: "Suites Mine chat o7 IA",
    client: "Andrea Mena",
    company: "Suites Mine",
    amount: 5000,
    currency: "MXN",
    stage: "negociacion",
    probability: 80,
    status: "open",
    closeDate: "2026-04-14",
    owner: "Lucia Herrera",
    aiPulse: true
  },
  {
    id: "deal-pipeline-018",
    pipelineId: "new-sales",
    title: "Integra365 licenciamiento regional",
    client: "Paula Cardenas",
    company: "Integra365",
    amount: 14800,
    currency: "EUR",
    stage: "negociacion",
    probability: 82,
    status: "open",
    closeDate: "2026-05-02",
    owner: "Valeria Cruz",
    aiPulse: false
  },
  {
    id: "deal-pipeline-019",
    pipelineId: "new-sales",
    title: "Contrato maintenance SEO",
    client: "Marion Leclerc",
    company: "LCQC",
    amount: 1200,
    currency: "USD",
    stage: "si-verbal",
    probability: 90,
    status: "open",
    closeDate: "2026-04-05",
    owner: "Lucia Herrera",
    aiPulse: false
  },
  {
    id: "deal-pipeline-020",
    pipelineId: "new-sales",
    title: "Portal reclutamiento Heliamerica",
    client: "Daniela Santos",
    company: "Heliamerica",
    amount: 9200,
    currency: "USD",
    stage: "si-verbal",
    probability: 92,
    status: "open",
    closeDate: "2026-04-10",
    owner: "Mateo Ruiz",
    aiPulse: true
  },
  {
    id: "deal-pipeline-021",
    pipelineId: "new-sales",
    title: "ERP rollout multi-site Bracco",
    client: "Eduardo Varela",
    company: "Bracco Ops",
    amount: 48000,
    currency: "USD",
    stage: "contrato",
    probability: 95,
    status: "open",
    closeDate: "2026-04-07",
    owner: "Valeria Cruz",
    aiPulse: true
  },
  {
    id: "deal-pipeline-022",
    pipelineId: "new-sales",
    title: "Transfer scheduled Catalina admin",
    client: "Catalina Vergas",
    company: "Cinco Seis",
    amount: 900,
    currency: "MXN",
    stage: "ganado",
    probability: 100,
    status: "won",
    closeDate: "2026-03-18",
    owner: "Lucia Herrera",
    aiPulse: false
  },
  {
    id: "deal-pipeline-023",
    pipelineId: "new-sales",
    title: "Villa de la Roca ajustes sitio",
    client: "Jacques Baldassari",
    company: "Villa de la Roca",
    amount: 75,
    currency: "USD",
    stage: "ganado",
    probability: 100,
    status: "won",
    closeDate: "2026-03-22",
    owner: "Mateo Ruiz",
    aiPulse: false
  },
  {
    id: "deal-pipeline-024",
    pipelineId: "new-sales",
    title: "Mesa de ayuda regional Atlas",
    client: "Rene Alvarez",
    company: "Atlas Mobility",
    amount: 6400,
    currency: "USD",
    stage: "perdido",
    probability: 0,
    status: "lost",
    closeDate: "2026-03-11",
    owner: "Valeria Cruz",
    aiPulse: false
  }
];
